name: Deploy on staging
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CI: true
  
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - name: Run function tests
        run: |
          cd functions
          yarn install --frozen-lockfile
          yarn test
      - run: yarn build
        env:
          REACT_APP_AUTH_PROVIDERS: google,twitter,github,facebook
          REACT_APP_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
          REACT_APP_STORAGE: ${{ secrets.DEV_FIREBASE_APP_STORAGE }}
          PUBLIC_URL: https://${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_GOOGLE_ANALYTICS_ID: ""
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  
  deploy:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/download-artifact@master
        with:
          name: build
      - run: |
          cd functions
          yarn install --frozen-lockfile
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --project=${{ secrets.DEV_FIREBASE_PROJECT_ID }} --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
  